### ISSUE TITLE
Hey, this is not an issue, but rather a question

### ISSUE THREAD

**Issue by dgudim** [m1zukash1/VGTU-app#1]
Hi, I recently tried fetching the timetable for my group with little to no luck, I basically want to know how you did it. I didn't find any way to contact you, so here are mine.
Discord: kloud#4022
Matrix: @doodetz:matrix.org

Looking forward to talking to you

**Comment by sausagenoods** [comment]
That's because the API backend is down. Has been that way for a while now.

**Comment by sausagenoods** [comment]
The API for mano vgtu app has changed. The endpoint for fetching timetables isn't available anymore. I guess I'll reverse it again when they release the new app.

**Comment by dgudim** [comment]
It's a funny story, they actually shut the app down because of me, I told them that the authentication to ws.vgtu.lt is done via http, which is you know, bad. I didn't find the endpoint though 🙃 and resorted to a daily cron scrape script.

**Comment by sausagenoods** [comment]
Well see the thing is, the old HTTP endpoint for authenticating and supplying tokens still work. Previously, they had debug mode (I think it was Laravel's) enabled with the highest verbosity option set and if you supplied a null password you could get it to leak the full name and password hash belonging to the username in the stack trace...

**Comment by dgudim** [comment]
Yeah, I've seen that thing with the full stack trace, pretty bruh. But I thought they disabled the api completely (at least that's what the told me the would do)

**Comment by dgudim** [comment]
Yo it really is still up with the debug traces
![Screenshot_20221120-231317_Chrome](https://user-images.githubusercontent.com/34401005/202926537-61dd91b2-1baf-460f-a120-d5a4369babb2.jpg)

**Comment by sausagenoods** [comment]
It's up with debug mode enabled. But if you set correct headers and send POST data it's down :)) Some hacky stuff right there.
`curl http://ws.vgtu.lt/api/auth/login`

The whole API isn't down, they're probably testing in production :D

**Comment by dgudim** [comment]
Yes, testing in production, why not :D Yolo after all
